/**
 * Blog content utilities.
 *
 * Reads SSG blog content from /content/blog/ at build time.
 * These files are generated by the backend auto-blog system.
 */

import fs from "fs";
import path from "path";

const CONTENT_DIR = path.join(process.cwd(), "content", "blog");
const POSTS_DIR = path.join(CONTENT_DIR, "posts");

// ---------------------------------------------------------------------------
// Types — mirrors backend/app/auto_blog/schemas.py
// ---------------------------------------------------------------------------

export interface FAQItem {
  question: string;
  answer: string;
}

export interface InternalLink {
  anchor_text: string;
  suggested_url: string;
  context: string;
}

export interface ExternalLink {
  anchor_text: string;
  url: string;
  rel: string;
}

export interface TOCEntry {
  id: string;
  text: string;
  level: number;
}

export interface AuthorInfo {
  name: string;
  bio: string;
  url: string;
}

export interface OpenGraphData {
  og_title: string;
  og_description: string;
  og_image: string;
  og_type: string;
  twitter_card: string;
}

export interface BreadcrumbItem {
  name: string;
  url: string;
}

export interface HreflangLink {
  hreflang: string;
  href: string;
}

export interface BlogPostMeta {
  // Core
  title: string;
  slug: string;
  locale: string;
  excerpt: string;

  // Head & metadata
  meta_title: string;
  meta_description: string;
  canonical_url: string;

  // Social
  open_graph: OpenGraphData;

  // E-E-A-T
  author: AuthorInfo;
  published_at: string;
  updated_at: string;

  // Content stats
  reading_time_minutes: number;
  word_count: number;
  featured_image: string | null;
  featured_image_alt: string;

  // Keywords & tags
  tags: string[];
  primary_keyword: string;
  secondary_keywords: string[];

  // Structure
  toc: TOCEntry[];

  // FAQ
  faq: FAQItem[];

  // Links
  internal_links: InternalLink[];
  external_links: ExternalLink[];

  // Navigation
  breadcrumbs: BreadcrumbItem[];
  hreflang_links: HreflangLink[];

  // Schema markup (JSON-LD)
  schema_article: Record<string, unknown>;
  schema_faq: Record<string, unknown>;
  schema_breadcrumb: Record<string, unknown>;
  schema_author: Record<string, unknown>;
}

export interface BlogPost {
  meta: BlogPostMeta;
  content: string;
}

export interface BlogIndexEntry {
  slug: string;
  title: string;
  excerpt: string;
  published_at: string;
  tags: string[];
  reading_time_minutes: number;
  featured_image: string | null;
  featured_image_alt: string;
  locale: string;
  primary_keyword: string;
}

export interface PostMeta {
  slug: string;
  languages: string[];
  hreflang_links: HreflangLink[];
  published_at: string;
  tags: string[];
}

// ---------------------------------------------------------------------------
// Data access functions
// ---------------------------------------------------------------------------

/**
 * Get the blog index for a specific locale.
 */
export function getBlogIndex(locale: string): BlogIndexEntry[] {
  const indexPath = path.join(CONTENT_DIR, "index.json");
  if (!fs.existsSync(indexPath)) {
    return [];
  }

  const index = JSON.parse(fs.readFileSync(indexPath, "utf-8"));
  return index[locale] || [];
}

/**
 * Get a specific blog post by slug and locale.
 */
export function getBlogPost(slug: string, locale: string): BlogPost | null {
  const postPath = path.join(POSTS_DIR, slug, `${locale}.json`);
  if (!fs.existsSync(postPath)) {
    return null;
  }

  return JSON.parse(fs.readFileSync(postPath, "utf-8"));
}

/**
 * Get all available post slugs (for static generation).
 */
export function getAllPostSlugs(): string[] {
  if (!fs.existsSync(POSTS_DIR)) {
    return [];
  }

  return fs
    .readdirSync(POSTS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
}

/**
 * Get post metadata (hreflang links, available languages).
 */
export function getPostMeta(slug: string): PostMeta | null {
  const metaPath = path.join(POSTS_DIR, slug, "meta.json");
  if (!fs.existsSync(metaPath)) {
    return null;
  }

  return JSON.parse(fs.readFileSync(metaPath, "utf-8"));
}
